version: '2'

services:
    applications:
      image: tianon/true
      volumes:
        - ${APPLICATION}:/var/www

    mysql:
      build:
        context: ./mysql
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      networks:
        - backend

    php-fpm:
      build:
        context: ./php-fpm
        args:
          - USER_PNAME=${USER_PNAME}
          - USER_PUID=${USER_PUID}
          - USER_PGID=${USER_PGID}
      volumes_from:
        - applications
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - "2375:2375"
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      depends_on:
        - mysql
        - rabbitmq
      environment:
        - APP_DOCKER_SOCKET_HOST=${APP_DOCKER_SOCKET_HOST}
      networks:
        - backend

    nginx:
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
      volumes_from:
        - applications
      volumes:
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

    rabbitmq:
      build: ./rabbitmq
      ports:
        - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
        - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
      privileged: true
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      networks:
        - backend

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

volumes:
  mysql:
    driver: "local"
  phpmyadmin:
    driver: "local"
