version: '2'
services:
  php-analyzer:
    scale: 1
    start_on_create: false
  app-php-fpm:
    scale: 1
    start_on_create: true
  nginx:
    scale: 1
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: nginx
        source_port: 8888
        target_port: 80
      config: |-
        global
            maxconn 4096
            maxpipes 1024
        nginx 80
            balance leastconn
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  mysql:
    scale: 1
    start_on_create: true
  app-nginx:
    scale: 1
    start_on_create: true
  php-fpm:
    scale: 1
    start_on_create: true
  rabbitmq:
    scale: 1
    start_on_create: true
